### ISSUE TITLE
[BUG] Kibana - Rules - Redunant tooltip on rule enalbe/disable switch

### ISSUE THREAD

**Issue by orouz** [elastic/cloudbeat#102] opened 2022-05-10 09:14 UTC
**Describe the bug**
Whenever a user hovers the toggle switch of a Rules table row, we show a tooltip to indicate the action: "activate" or "deactivate" depending on the current status.

after clicking the toggle switch, the tooltip remains visible.

*The tooltip should be completely removed.*

**Preconditions**

- CIS Kuberenetes Integration installed

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Go to "Cloud Security Posture"
2. Go to "My Benchmarks"
3. Click on an integration name to go to its rules page
4. Click on a toggle switch of one of the rules row

**Expected behavior**

No tooltip at all on the switch in the rules table

**Screenshots**
![Screen Shot 2022-05-10 at 12 10 35](https://user-images.githubusercontent.com/20814186/167593182-07c96b8e-c36d-4e6c-908d-4275b02e2522.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: `Version 101.0.4951.54 (Official Build) (arm64)`
 - Kibana Version:  `df225b213b188c81888141cee2ec191424fc0649`
 - Endpoint Version:
 - Other Version: 

**Additional context**

- issue needs to be moved from `cloudbeat`

**Comment by kfirpeled** [comment] 2022-05-12 12:05
This is eui design - we can close it @tehilashn

**Comment by tinnytintin10** [comment] 2022-05-13 18:24
@kfirpeled while this is in line with EUI, IMO it's still a bug so we shouldn't close it. The persistent mouseover text affects usability directly by potentially hiding some enable/disable toggles, see video below: 

https://user-images.githubusercontent.com/53792284/167947306-de0b7f32-6601-45f0-a50b-8a4fa798d1c2.mov

You see similar behavior on the alerts page but only if a user double clicks on the action. After one click, the mouseover text disappears (unlike ours where it persists) : 

https://user-images.githubusercontent.com/53792284/168344088-4ec9eae3-e76e-44c3-a836-311555ce39ed.mov

The expected behavior here should be that the mouseover text disappears when the user hovers away or clicks the action. lmk what you think.

**Comment by tinnytintin10** [comment] 2022-05-13 18:56
That being said, I have changed the priority on this from a 4 (waiting on product) to a 3. We should aim to get this sorted by 8.4 - we can get away with little annoyances like this for 8.3 since we're behind a feature flag, however, let's make sure we're polished for 8.4.

**Comment by kfirpeled** [comment] 2022-05-22 15:52
Showing you how eui behaves on focus. It is definitely keeps showing the tooltip. Only when i'm hovering on something else that creates a tooltip. It removes the focus from the previous one.
So unless it is not the same behavior, we have here something to fix. 

https://user-images.githubusercontent.com/61654899/169704177-7a7abab9-1629-42c1-8ed1-2e732db094f2.mov

**Comment by kfirpeled** [comment] 2022-05-22 15:53
Hey @tinnytintin10 from the attached video I now understand the problem. Thanks

**Comment by orouz** [comment] 2022-06-07 11:20
a more fitting example is the rules view in security where they have roughly the same cell - with a switch. 
also note, we use `EuiBasicTable` so comparing with `EuiDataGrid` isn't exactly the same. 

they solve it by just not having a tooltip there :).  i suggest we do the same. 

the value the user gets from having a tooltip say "activate" or "deactivate" is already marginal at best (as switch buttons are common enough to understand instantly) 

so if this tooltip would have 0 issues i'd be worth it IMO
now it requires exploring and unless the solution will come from upstream or be a very simple workaround, i think it's just not worth it.

@kfirpeled @tinnytintin10 @einatjacoby 

wdyt?

**Comment by tinnytintin10** [comment] 2022-06-07 16:38
@orouz nice write-up! Let's remove it.

**Comment by orouz** [comment] 2022-06-08 09:51
PR 
- https://github.com/elastic/kibana/pull/133860

**Closed** 2022-06-08 13:55 UTC
Labels: bug, csp: last mile, 8.4 candidate

**Comment by gurevichdmitry** [comment] 2022-07-31 16:04
Verified on Kibana 8.4 BC-1 version, build 58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d - fixed.
The tooltip does not appear.
