### ISSUE TITLE
[BUG] Kibana - Findings - New search does not return the user to the first page

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#99] opened 2022-05-10 06:31 UTC
**Describe the bug**
The user remains on the same page when a new search is applied.

**Preconditions**
Kibana + ES + CIS k8s benchmark integration installed.
Elastic Agent deployed on a K8s cluster.

**To Reproduce**
1. Open Kibana and navigate to the Cloud Security section.
2. Go to the Findings page.
3. Navigate to a random page.
4. Apply a search query that returns results.
5. User remains on the same page.

**Expected behavior**
After applying a new search the user returns to the first page.

 - Kibana Version: 8.3.0-SNAPSHOT

**Comment by tehilashn** [comment] 2022-05-11 11:51
duplicate of https://github.com/elastic/cloudbeat/issues/98

**Closed** 2022-05-11 12:28 UTC
Labels: bug, csp: last mile
