### ISSUE TITLE
[BUG] Benchmark table doesn't show active rule count 

### ISSUE THREAD

**Issue by tinnytintin10** [elastic/cloudbeat#161] opened 2022-05-19 11:41 UTC
**Describe the bug**

The table on the Benchmark Integrations table has a column called `Active Rules` that should show the number of active/enabled rules. Currently, the table doesn't show anything under this column, it's always blank. 

**Expected behavior**

Show the number of active/enabled rules in the benchmark integration 

**Screenshots**

<img width="1624" alt="Screen Shot 2022-05-19 at 2 43 18 PM" src="https://user-images.githubusercontent.com/53792284/169285605-bca06329-4ad6-4430-8af4-6c8e2b630d8d.png">

**Comment by kfirpeled** [comment] 2022-05-22 10:01
When fixing it, please move the column of active rules to be the second column as figma suggests

<img width="939" alt="Screen Shot 2022-05-22 at 13 01 04" src="https://user-images.githubusercontent.com/61654899/169690010-5c49faa8-fa7d-4391-bd70-b29122295238.png">

**Comment by tehilashn** [comment] 2022-05-24 10:12
this is a duplicate of https://github.com/elastic/security-team/issues/3607, keeping this one

**Closed** 2022-05-26 12:01 UTC
Labels: bug, csp: last mile, 8.3 candidate
