### ISSUE TITLE
[BUG] Kibana - Findings - Search error results with crash & printed stack trace

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#100] opened 2022-05-10 07:21 UTC
**Describe the bug**
When making a search error, e.g. without adding an operator between two statements (`resource_id.keyword : "x" resource_id.keyword : "y"`), the stack trace is printed to the screen.

**Preconditions**
Kibana + ES + CIS k8s benchmark integration is installed.
Elastic Agent deployed on a K8s cluster.

**To Reproduce**

1. Open Kibana and navigate to the Cloud Security section.
2. Go to the Findings page.
3.  Apply the following query to the search bar:
`resource_id.keyword : "x" resource_id.keyword : "y`

**Expected behavior**
Catch the error and present it to the user without affecting the previous table state.

**Screenshots**
Current:

![Screen Shot 2022-05-10 at 9 55 37](https://user-images.githubusercontent.com/68195305/167571401-50be8224-ad33-4687-b0a2-2072f6657ce7.png)

From the Discover page:
A popup pops with the relevant error and stack trace.
![Screen Shot 2022-05-10 at 10 18 34](https://user-images.githubusercontent.com/68195305/167571690-6eda4268-eafa-445f-8a43-3a2c4efbc8f7.png)

 Kibana Version: 8.3.0-SNAPSHOT

**Comment by orouz** [comment] 2022-05-10 11:28
this is the same as 

https://github.com/elastic/kibana/blob/50a504232f19360c98c3fa16457c742b968cd674/x-pack/plugins/cloud_security_posture/public/pages/findings/utils.ts#L18-L21

also tracked here - https://github.com/elastic/security-team/issues/3591

**Comment by JordanSh** [comment] 2022-05-10 14:40
closing as duplicate of https://github.com/elastic/security-team/issues/3591

**Closed by JordanSh** 2022-05-10 14:40 UTC
Labels: bug, csp: last mile
