### ISSUE TITLE
[BUG] Elastic-Agent displays wrong user/group owner on file as part of remediation 

### ISSUE THREAD

**Issue by DaveSys911** [elastic/cloudbeat#115] opened 2022-05-11 08:35 UTC
**Describe the bug**
Write a detailed description of the observer behavior using the actions you performed.
After remediation of user/group owner on file or directory agent has issues recognizing the new owner correctly(Might be related if the user/group aren't present on elastic-agent itself).
**Preconditions**
Environment state and/or platform specific configurations.
Elk running & agent deployed

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Change owner of /var/lib/etcd to etcd:etcd on kind master node

**Expected behavior**
For rule to display as passed & evidence to show file now owned by etcd:etcd

**Screenshots**
![image](https://user-images.githubusercontent.com/16253938/167805431-372ef22f-e963-46ff-9333-2390bcc41feb.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome 
 - Kibana Version: 
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/16253938/167805685-cc766a19-4a13-4515-8451-8d4208441211.png">

 - Endpoint Version:
 Elastic-agent commit sha b863837b7fafc4189aa2ba079098c915dcc38370 version: 8.3.0-SNAPSHOT
 - Other Version: 

**Additional context**

**Comment by oren-zohar** [comment] 2022-05-11 08:59
can you share the json raw resource please?

**Comment by DaveSys911** [comment] 2022-05-12 08:57
See below, The problem occurred when i had to create the etcd user on the kind node. Basically, the numeric value of the UID/GID of etcd on the kind node, is the same as the "elastic-agent" user on the agent pod.

Stat output on  node
![image](https://user-images.githubusercontent.com/16253938/168032448-8c9ee85f-4558-4230-b485-670480e11edf.png)

Stat output on pod
<img width="878" alt="image" src="https://user-images.githubusercontent.com/16253938/168032429-f691cfdb-13c5-418a-ad0e-283079435911.png">

<details><summary>Raw finding json</summary>
```json
{
  "result": {
    "evaluation": "failed",
    "evidence": {
      "uid": "",
      "gid": "elastic-agent"
    },
    "expected": {
      "uid": "etcd",
      "gid": "etcd"
    }
  },
  "agent": {
    "name": "kind-multi-control-plane",
    "id": "90f136d5-96ea-41bd-a25a-fa1d9e3f409e",
    "ephemeral_id": "b6f798cc-027e-43e4-886f-ad263af1c05a",
    "type": "cloudbeat",
    "version": "8.3.0"
  },
  "cluster_id": "68f3e520-f532-4208-9e8b-8cbb67f75613",
  "cycle_id": "b3ca86a7-600c-4114-9cf1-afb26b5c03be",
  "@timestamp": "2022-05-12T08:44:19.286Z",
  "ecs": {
    "version": "8.0.0"
  },
  "resource": {
    "sub_type": "directory",
    "name": "/hostfs/var/lib/etcd",
    "raw": {
      "inode": "4730906",
      "mode": "700",
      "path": "/hostfs/var/lib/etcd",
      "uid": "",
      "filename": "etcd",
      "gid": "elastic-agent",
      "sub_type": "directory"
    },
    "id": "fa345cec-859a-5b88-a6de-e238910ccfc3",
    "type": "file"
  },
  "host": {
    "hostname": "kind-multi-control-plane",
    "os": {
      "kernel": "5.10.47-linuxkit",
      "codename": "focal",
      "name": "Ubuntu",
      "type": "linux",
      "family": "debian",
      "version": "20.04.4 LTS (Focal Fossa)",
      "platform": "ubuntu"
    },
    "containerized": true,
    "ip": [
      "10.244.0.1",
      "10.244.0.1",
      "10.244.0.1",
      "172.18.0.3",
      "fc00:f853:ccd:e793::3",
      "fe80::42:acff:fe12:3"
    ],
    "name": "kind-multi-control-plane",
    "mac": [
      "02:42:ac:12:00:03",
      "6a:17:48:1c:52:96",
      "d6:11:c7:a5:ec:8e",
      "f2:4c:bc:35:3a:33"
    ],
    "architecture": "aarch64"
  },
  "rule": {
    "references": "1. [https://coreos.com/etcd/docs/latest/op-guide/configuration.html#data-dir](https://coreos.com/etcd/docs/latest/op-guide/configuration.html#data-dir)\n2. [https://kubernetes.io/docs/admin/etcd/](https://kubernetes.io/docs/admin/etcd/)\n",
    "impact": "None\n",
    "description": "Ensure that the etcd data directory ownership is set to `etcd:etcd`.\n",
    "section": "Control Plane Node Configuration Files",
    "default_value": "By default, etcd data directory ownership is set to `etcd:etcd`.\n",
    "version": "1.0",
    "rationale": "etcd is a highly-available key-value store used by Kubernetes deployments for persistent storage of all of its REST API objects. This data directory should be protected from any unauthorized reads or writes. It should be owned by `etcd:etcd`.\n",
    "benchmark": {
      "name": "CIS Kubernetes V1.23",
      "version": "v1.0.0"
    },
    "tags": [
      "CIS",
      "Kubernetes",
      "CIS 1.1.12",
      "Control Plane Node Configuration Files"
    ],
    "remediation": "On the etcd server node, get the etcd data directory, passed as an argument\n`--data-dir`,\nfrom the below command:\n```\nps -ef | grep etcd\n```\nRun the below command (based on the etcd data directory found above). For example,\n```\nchown etcd:etcd /var/lib/etcd\n```\n",
    "audit": "On the etcd server node, get the etcd data directory, passed as an argument\n`--data-dir`,\nfrom the below command:\n```\nps -ef | grep etcd\n```\nRun the below command (based on the etcd data directory found above). For example,\n```\nstat -c %U:%G /var/lib/etcd\n```\nVerify that the ownership is set to `etcd:etcd`.\n",
    "name": "Ensure that the etcd data directory ownership is set to etcd:etcd (Automated)",
    "id": "1a5c8f4f-fc22-5c1e-b7e1-affa0f03edf0",
    "profile_applicability": "* Level 1 - Master Node\n"
  },
  "resource_id": "fa345cec-859a-5b88-a6de-e238910ccfc3",
  "type": "file",
  "event": {
    "agent_id_status": "mismatch",
    "ingested": "2022-05-12T08:44:21Z"
  }
}
```
</details>

**Comment by eyalkraft** [comment] 2022-05-16 09:22
@DaveSys911 just be sure
The problem here is not in the remediation specifically, but a more general bug in the way cloudbeat determines the owner of a file - correct?

I remember we had a working demo with changing a file permissions.. Did we never went as far as testing ownership changes as well?

If cloudbeat actually never determined file ownership correctly so:
1. This is a high priority bug. Let's rename the issue "[BUG] cloudbeat mounted files wrong ownership" since it's not only a matter of displaying or remediation.
2. this is tightly linked to https://github.com/elastic/cloudbeat/issues/118

cc @uri-weisman

**Comment by uri-weisman** [comment] 2022-05-19 05:50
Duplicate of https://github.com/elastic/cloudbeat/issues/118

**Closed by uri-weisman** 2022-05-19 05:50 UTC
Labels: bug, csp: last mile
