### ISSUE TITLE
[BUG] Dashboard page does not show a loading state when integration not installed

### ISSUE THREAD

**Issue by ari-aviran** [elastic/cloudbeat#107] opened 2022-05-10 12:51 UTC
**Describe the bug**
When the dashboard page loads before the integration is installed, it does not show a loading state (spinner/whatever)

**Preconditions**
- Kibana up and running
- CSP plugin enabled
- Integration **not** installed

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Go to dashboard page
2. Notice there is no loading state before the blank page graphic is displayed

**Expected behavior**
Loading state should be presented while the page is loading

**Screenshots**

https://user-images.githubusercontent.com/94899776/167632375-e972c9df-0d55-409b-ae9a-516ae705fd3e.mov

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: VERSION: 8.3.0 BUILD: 52512 COMMIT: df225b213b188c81888141cee2ec191424fc0649
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by JordanSh** [comment] 2022-06-20 10:49
- https://github.com/elastic/kibana/pull/132432
This PR addressed and fixed those issues
I'm adding a video of the current state and closing since this cannot be reproduced anymore


https://user-images.githubusercontent.com/51442161/174585984-b7c87d90-bd93-40bb-b21e-95ddbc668488.mov

**Closed by JordanSh** 2022-06-20 10:49 UTC
Labels: bug, csp: last mile, 8.4 candidate

**Comment by orouz** [comment] 2022-07-31 09:39
tested on [`58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d` ](https://github.com/elastic/kibana/commits/58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d)

there's a small issue where the card's button is not disabled while the rest of the card is 

https://user-images.githubusercontent.com/20814186/182020317-d898e84f-c9e2-4dfa-83c6-4a335385b91a.mov

we can fix it in fleet ui

https://github.com/elastic/kibana/blob/58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d/src/plugins/kibana_react/public/page_template/no_data_page/no_data_card/elastic_agent_card.tsx#L90

by adding `isDisabled`
