### ISSUE TITLE
[BUG] cloudbeat not getting dowloaded when integration is installed and manifest applied 

### ISSUE THREAD

**Issue by tinnytintin10** [elastic/cloudbeat#205] opened 2022-06-03 16:40 UTC
**Describe the bug**

Cloudbeat isn't getting successfully downloaded by the elastic agent upon installation. Without cloudbeat evaluations can't be performed and therefore no findings are generated. 

**Preconditions**
8.3 snapshot in ESS (cloud) 

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Deploy the 8.3 snapshots in cloud
2. install our integration 
3. apply generated manifest to k8s cluster 

**Expected behavior**

Cloudbeat gets downloaded and installed successfully. 

**logs screenshots**

<details> 

command: `root@kind-control-plane:/usr/share/elastic-agent/state/data/logs# cat elastic-agent-20220603.ndjson | grep error | head`

<summary> first 10 </summary> 

```

{"log.level":"error","@timestamp":"2022-06-03T16:13:44.067Z","log.origin":{"file.name":"status/reporter.go","file.line":236},"message":"Elastic Agent status changed to: 'error'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-06-03T16:13:44.067Z","log.origin":{"file.name":"operation/operation_retryable.go","file.line":85},"message":"operation operation-fetch failed, err: 3 errors occurred:\n\t* package '/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' not found: open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz: no such file or directory\n\t* call to 'https://snapshots.elastic.co/8.3.0-378ebcca/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\t* call to 'https://artifacts.elastic.co/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-06-03T16:13:44.067Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2022-06-03T16:13:44Z - message: Application: cloudbeat--8.3.0-SNAPSHOT[eb82a2cb-b3ab-4567-8b63-6e261f0ea6d7]: State changed to FAILED: 3 errors occurred:\n\t* package '/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' not found: open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz: no such file or directory\n\t* call to 'https://snapshots.elastic.co/8.3.0-378ebcca/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\t* call to 'https://artifacts.elastic.co/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\n - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-06-03T16:13:44.067Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":208},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: 3 errors occurred:\n\t* package '/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' not found: open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz: no such file or directory\n\t* call to 'https://snapshots.elastic.co/8.3.0-378ebcca/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\t* call to 'https://artifacts.elastic.co/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\n: 3 errors occurred:\n\t* package '/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' not found: open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz: no such file or directory\n\t* call to 'https://snapshots.elastic.co/8.3.0-378ebcca/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\t* call to 'https://artifacts.elastic.co/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-06-03T16:13:44.205Z","log.origin":{"file.name":"operation/operation_retryable.go","file.line":85},"message":"operation operation-verify failed, err: operation 'operation-verify' failed to verify cloudbeat.8.3.0-SNAPSHOT: 3 errors occurred:\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-06-03T16:13:44.205Z","log.origin":{"file.name":"emitter/controller.go","file.line":123},"message":"Failed to render configuration with latest context from composable controller: operator: failed to execute step sc-run, error: operation 'operation-verify' failed to verify cloudbeat.8.3.0-SNAPSHOT: 3 errors occurred:\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\n: operation 'operation-verify' failed to verify cloudbeat.8.3.0-SNAPSHOT: 3 errors occurred:\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-06-03T16:13:44.205Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2022-06-03T16:13:44Z - message: Application: cloudbeat--8.3.0-SNAPSHOT[eb82a2cb-b3ab-4567-8b63-6e261f0ea6d7]: State changed to FAILED: operation 'operation-verify' failed to verify cloudbeat.8.3.0-SNAPSHOT: 3 errors occurred:\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\n - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-06-03T16:13:46.479Z","log.origin":{"file.name":"operation/operation_retryable.go","file.line":85},"message":"operation operation-verify failed, err: operation 'operation-verify' failed to verify cloudbeat.8.3.0-SNAPSHOT: 3 errors occurred:\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-06-03T16:13:46.479Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":208},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'operation-verify' failed to verify cloudbeat.8.3.0-SNAPSHOT: 3 errors occurred:\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\n: operation 'operation-verify' failed to verify cloudbeat.8.3.0-SNAPSHOT: 3 errors occurred:\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-06-03T16:13:48.740Z","log.origin":{"file.name":"operation/operation_retryable.go","file.line":85},"message":"operation operation-verify failed, err: operation 'operation-verify' failed to verify cloudbeat.8.3.0-SNAPSHOT: 3 errors occurred:\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\t* failed to open checksum file \"/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512\": open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz.sha512: no such file or directory\n\n","ecs.version":"1.6.0"}

```

</details>

<details> 

command: `root@minikube:/usr/share/elastic-agent/state/data/logs# cat elastic-agent-20220603.ndjson | grep cloudbeat | grep 404`

<summary> logs of cloudbeat not getting downloaded successfully </summary> 

```

{"log.level":"error","@timestamp":"2022-06-03T16:19:59.066Z","log.origin":{"file.name":"operation/operation_retryable.go","file.line":85},"message":"operation operation-fetch failed, err: 3 errors occurred:\n\t* package '/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' not found: open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz: no such file or directory\n\t* call to 'https://snapshots.elastic.co/8.3.0-378ebcca/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\t* call to 'https://artifacts.elastic.co/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-06-03T16:19:59.066Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2022-06-03T16:19:59Z - message: Application: cloudbeat--8.3.0-SNAPSHOT[3f6ddd9b-dc5c-431c-9829-c6039f0d628c]: State changed to FAILED: 3 errors occurred:\n\t* package '/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' not found: open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz: no such file or directory\n\t* call to 'https://snapshots.elastic.co/8.3.0-378ebcca/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\t* call to 'https://artifacts.elastic.co/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\n - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-06-03T16:19:59.066Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":208},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: 3 errors occurred:\n\t* package '/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' not found: open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz: no such file or directory\n\t* call to 'https://snapshots.elastic.co/8.3.0-378ebcca/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\t* call to 'https://artifacts.elastic.co/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\n: 3 errors occurred:\n\t* package '/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' not found: open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz: no such file or directory\n\t* call to 'https://snapshots.elastic.co/8.3.0-378ebcca/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\t* call to 'https://artifacts.elastic.co/downloads/cloudbeat/cloudbeat-8.3.0-SNAPSHOT-linux-arm64.tar.gz' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}

```

</details>

**Comment by tinnytintin10** [comment] 2022-06-03 16:44
[here](https://github.com/elastic/kibana/commits/25476b531ba9f32292bde85508d342aa5e1c29eb) is the last commit of the snapshot i used to create the deployment.

**Comment by tinnytintin10** [comment] 2022-06-03 16:46
@yashtewari as you work on this can you put your updates here, thanks!

**Comment by tinnytintin10** [comment] 2022-06-04 15:35
https://github.com/elastic/infra/pull/36299 for tracking purposes

**Comment by yashtewari** [comment] 2022-06-07 08:40
So cloudbeat was missing from those build files created for 8.3 staging builds and 8.3 snapshots which get built from all the `8.3` side branches in all the repos of the stack. The PR above fixes this.

After merge, got a build that seems to be failing: https://internal-ci.elastic.co/job/elastic+unified-release+master+staging-cloudbeat-8.3/

@jmlrt thinks the issue is on their side, and is looking. Thanks Julien!

**Comment by yashtewari** [comment] 2022-06-07 08:48
For tracking: https://github.com/elastic/infra/pull/36306

**Comment by yashtewari** [comment] 2022-06-07 10:03
Looks like after the merge, cloudbeat was built successfully in this Build Candidate build: https://internal-ci.elastic.co/job/elastic+unified-release+master+staging-multijob-8.3/7/

**Comment by tinnytintin10** [comment] 2022-06-07 16:52
@yashtewari I will create an 8.3 deployment in ESS and test out that everything works as expected- if all goes well I will close this issue out 🙌🏾

**Comment by yashtewari** [comment] 2022-06-09 08:04
Above has fixed the problem for ESS `8.3.0-SNAPSHOT` with image `docker.elastic.co/elastic-agent/elastic-agent:8.3.0-a70058df`

But not for the release candidate on ESS `8.3.0 (latest)` with image `docker.elastic.co/staging/elastic-agent:8.3.0-a70058df`

Failure log from the agent:
```
{"log.level":"error","@timestamp":"2022-06-09T07:26:51.530Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":208},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: 2 errors occurred:\n\t* package '/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-linux-x86_64.tar.gz' not found: open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-linux-x86_64.tar.gz: no such file or directory\n\t* call to 'https://artifacts.elastic.co/downloads/cloudbeat/cloudbeat-8.3.0-linux-x86_64.tar.gz' returned unsuccessful status code: 404\n\n: 2 errors occurred:\n\t* package '/usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-linux-x86_64.tar.gz' not found: open /usr/share/elastic-agent/state/data/downloads/cloudbeat-8.3.0-linux-x86_64.tar.gz: no such file or directory\n\t* call to 'https://artifacts.elastic.co/downloads/cloudbeat/cloudbeat-8.3.0-linux-x86_64.tar.gz' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
```

I think there's still work to do in order to get cloudbeat on the Artifacts API for the release candidates, and eventually the release.

**Comment by yashtewari** [comment] 2022-06-09 08:31
My bad @jmlrt, did some experiments to confirm that it's not a problem with the Artifacts API.

The release candidate Agent is looking for artifacts at `https://artifacts.elastic.co/downloads`, which I'm assuming is the production API, so it's not just cloudbeat that won't get downloaded, nothing can get downloaded until the actual release.

The Agent is able to deal with this by having all the beats _pre-installed in the Agent image_. For unrelated reasons, cloudbeat is not part of this pre-packaging.

I think given that the solution is verified by testing with ESS `8.3.0-SNAPSHOT`, we can close this issue. Thanks again for your help @mgreau @jmlrt!!

**Comment by jmlrt** [comment] 2022-06-09 08:45
> For unrelated reasons, cloudbeat is not part of this pre-packaging.

AFAIK, the code to pre-install artifacts is in the release-manager.
Example for APM Server: 

https://github.com/elastic/infra/blob/26bb9106a091d933f5c1de1f1ddc03ad2f1a4fc4/cd/release/release-manager/project-configs/8.3/elastic-agent.gradle#L202-L219

I'm not sure if that's something we can still do for the next BC or if it's too late.

**Comment by jmlrt** [comment] 2022-06-09 08:48
Please confirm if cloudbeat is supposed to be pre-installed and I can try to create a PR if needed.

**Comment by jmlrt** [comment] 2022-06-09 09:55
Elastic Agent BC build should fail if any of the artifacts to pre-install isn't available. So it would have been discovered during the first BC build.

**Comment by DaveSys911** [comment] 2022-06-09 22:28
@jmlrt agent doesn't support downloading staging builds, so if you could open that pr to pre-install cloudbeat like the apm example.

One thing to note, Unlike the other beats we only produce Linux-amd64 & Linux-arm64 artifacts. I guess it needs to be accommodated in that Gradle file. So it won't break the builds for the other platforms.

**Closed** 2022-06-14 09:45 UTC
Labels: bug, csp: last mile

**Comment by uri-weisman** [comment] 2022-06-21 14:18
Verified with 8.3.0
